# Generated by Django 3.2 on 2023-01-18 08:48

from django.db import migrations, models
import django.utils.timezone
import users.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('fullname', models.CharField(max_length=50, verbose_name='Fullname')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('assistant', 'Assistant'), ('admin', 'Admin'), ('adviser', 'Adviser'), ('user', 'User'), ('none', 'None')], default='none', max_length=9, verbose_name='Role')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_codes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Access Codes')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.manager.CustomUserManager()),
            ],
        ),
    ]
