# Generated by Django 3.2 on 2023-01-19 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date and Time')),
                ('low_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_history_low', to=settings.AUTH_USER_MODEL, verbose_name='Low User')),
                ('up_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_history_up', to=settings.AUTH_USER_MODEL, verbose_name='Up User')),
            ],
        ),
    ]
