# Generated by Django 3.2 on 2023-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_history',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
