# Generated by Django 3.2 on 2023-01-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_history_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
