# Generated by Django 3.2 on 2023-01-18 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Sell_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Owner Name')),
                ('owner_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Owner Phone')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Street')),
                ('plaque', models.CharField(blank=True, max_length=10, null=True, verbose_name='Plaque')),
                ('floors', models.CharField(blank=True, max_length=10, null=True, verbose_name='Floors')),
                ('meterage', models.IntegerField(blank=True, default=0, null=True, verbose_name='Meterage')),
                ('price_per_meter', models.IntegerField(blank=True, default=0, null=True, verbose_name='Price Per Meterage')),
                ('total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Price')),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer Name')),
                ('style', models.CharField(blank=True, max_length=20, null=True, verbose_name='Style')),
                ('heating', models.CharField(blank=True, max_length=20, null=True, verbose_name='Heating')),
                ('bottom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bottom')),
                ('kitchen', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kitchen')),
                ('faucets', models.CharField(blank=True, max_length=20, null=True, verbose_name='Faucets')),
                ('bathtub', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bathtub')),
                ('window', models.CharField(blank=True, max_length=20, null=True, verbose_name='Window')),
                ('electricity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Electricity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.BooleanField(default=False, verbose_name='Status Home')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator User')),
            ],
        ),
    ]
