# Generated by Django 3.2 on 2023-01-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_sell_home',
            name='area_code',
            field=models.CharField(default=None, max_length=10, verbose_name='Area Code'),
            preserve_default=False,
        ),
    ]
