# Generated by Django 3.2 on 2023-01-18 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0002_buy_sell_home_area_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_sell_home',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_sell_home_accepted_by', to=settings.AUTH_USER_MODEL, verbose_name='Accepted By'),
        ),
        migrations.AddField(
            model_name='buy_sell_home',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accepted Date'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_sell_home_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
    ]
