# Generated by Django 3.2 on 2023-01-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20230118_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_sell_home',
            old_name='accepted_by',
            new_name='checked_by',
        ),
        migrations.RenameField(
            model_name='buy_sell_home',
            old_name='accepted_date',
            new_name='checked_date',
        ),
    ]
