# Generated by Django 3.2 on 2023-01-19 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0004_auto_20230118_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_history_home', to='estate.buy_sell_home', verbose_name='Buy-Sell-Home')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_history_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
