# Generated by Django 3.2 on 2023-01-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_home_history_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_sell_home',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Date'),
        ),
    ]
