# Generated by Django 3.2 on 2023-01-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_buy_sell_home_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_sell_home',
            name='area_code',
            field=models.CharField(max_length=100, verbose_name='Area Code'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='bathtub',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bathtub'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='bottom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bottom'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='electricity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Electricity'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='faucets',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Faucets'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='floors',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Floors'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='heating',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Heating'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='kitchen',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kitchen'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='plaque',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plaque'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='street',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='style',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='buy_sell_home',
            name='window',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Window'),
        ),
    ]
